name: Deploy Static Website to EC2 (Docker)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Image
        run: |
          docker build -t my-static-site .

      - name: Verify Docker image contents
        run: |
          docker run --rm my-static-site ls /usr/share/nginx/html

      - name: Save Docker image as tar file
        run: |
          mkdir -p docker-images
          docker save my-static-site:latest -o docker-images/my-static-site.tar
          ls -lh docker-images/

      - name: Verify tar file exists
        run: |
          if [ ! -f docker-images/my-static-site.tar ]; then
            echo "Docker image tar file not found!"
            exit 1
          fi

      - name: Upload Docker image to EC2
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          source: "docker-images/my-static-site.tar"
          target: "/home/ubuntu/docker-images/"
          strip_components: 0
          rm: false
          debug: true

      - name: SSH into EC2 and deploy Docker container
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e
            cd /home/ubuntu/docker-images
            docker load -i my-static-site.tar
            docker stop my-static-site-container || true
            docker rm my-static-site-container || true
            docker run -d -p 80:80 --name my-static-site-container my-static-site:latest
