name: Deploy Static Website to EC2 (Docker)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Step 3: Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t my-static-site .

      # Step 4: Verify Docker image contents
      - name: Verify Docker image contents
        run: |
          docker run --rm my-static-site ls /usr/share/nginx/html

      # Step 5: Save Docker image as tar file in root
      - name: Save Docker image as tar file
        run: |
          docker save my-static-site:latest -o my-static-site.tar
          chmod +r my-static-site.tar
          ls -lh my-static-site.tar

      # Step 6: Upload Docker image to EC2
      - name: Upload Docker image to EC2
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY
