name: Deploy Static Website to EC2 (Docker)

on:
  push:
    branches:
      - main  # This triggers the workflow when you push to 'main'

jobs:
  build:
    runs-on: ubuntu-latest  # GitHub Actions will run this job on an Ubuntu runner

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx (for building images)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Step 3: Build the Docker image
      - name: Build Docker Image
        run: |
          docker build -t my-static-site .  # Dockerfile should be in the root directory

      # Step 4: Save the Docker image to a tar file
      - name: Save Docker image as tar file
        run: |
